nginx:
    restart: always
    build: ./nginx/
    ports:
        - 80:80
    volumes:
        - /www/static
    volumes_from:
        - eve
    links:
        - eve:eve
        - swagger_ui:swagger_ui

swagger_ui:
    image: swaggerapi/swagger-ui:v3.0.12
    env-file: .env

eve:
    restart: always
    env-file: .env
    build: eve-app
    expose:
        - 5000
    ports:
        - 5000
    volumes:
        - ./eve-app:/usr/src/app 
        - /usr/src/app/static
    links:
        - mongodb
    command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app

mongodb:
  image: mongo
  expose:
    - 27017
  ports:
    - 27017
